### PR TITLE
Zipkin receiver for k8s

### PR DESCRIPTION
**Pull request by owais**
Most of this code will be removed after I refactor the upstream zipkinreceiver a bit.

### CODE REVIEW

**Comment by owais** [comment]
I'm gonna merge and take care of comments in next PR. This is kind of urgent

**Comment by dmitryax** [comment]
LGTM :)

**Comment by tigrannajaryan** [comment]
> Most of this code will be removed after I refactor the upstream zipkinreceiver a bit.

@owais Can you add an issue in the upstream to do this? I want to avoid adding any more code to this repo and move as much functionality as possible to the upstream.

**Comment by owais** [comment]
This is part of the kubernetes tagging feature and will be removed once we migrate that to contrib.

**Pull request merged**
